#!/usr/bin/env bash
#
# by Robert Plestenjak, robert.plestenjak@xlab.si
# by Stanislav Petr, glux@glux.org
# by Krzysztof Suszynski, krzysztof.suszynski@coi.gov.pl
#
# depends on: parted cloud-utils

set -eo pipefail

REPODIR="$( dirname "${BASH_SOURCE[0]}" )"
source "${REPODIR}/source/loader.bash"

loader_flag "${BASH_SOURCE[0]}"
loader_addpath "${REPODIR}/source"

include view.bash
include install-prerequisites.bash
include modify-initrd.bash
include modify-grub.bash

loader_finish

view.welcome
install-prerequisites
modify-initrd
modify-grub
view.farewell

exit 0
