#this will be the absolute path to lib based on the calling __FILE__
lib = File.expand_path('../lib', __FILE__)
#this will include the path in $LOAD_PATH unless it is already included
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'rspec/core/rake_task'
require 'centrifuge/raketask'

RSpec::Core::RakeTask.new(:spec)
Centrifuge::RakeTask.new do |t|
  t.size = { size: 120, unit: :GiB }
  t.vagrantfile = File.expand_path('../Vagrantfile', __FILE__)
end
